### ISSUE TITLE
java-consumer-client

### ISSUE THREAD

**Issue by pietrorosa** [bluzone/consumer-service#2]
Hi,
I am successfully connected our WS client to wss://bluzone.io/portal/consumer/location.
Is there a way we can **read** some test content about location data? How can I simulate location data published on the websocket?

Tnks.

BB,
Pietro.

**Comment by robert-dare** [comment]
Hi Pietro,

There is not currently a way to simulate location stream data.  Since you
control the interface implementation, you can simulate it on your end by
generating json messages.

Regards,

Robert

**Comment by pietrorosa** [comment]
Hi,
the method main of the Application Class creates the connection to location and send at message. 
Is possible create another process that it connect at WebSocket of location for retrieve this message? 
if possible, How can it be done? 

Tnks,
Pietro.

**Comment by robert-dare** [comment]
You can either create multiple instances of this client, or use it as an example in your code to spin up different client instances to different endpoints.
