### ISSUE TITLE
Cannot create many policies in Bluzone cloud.

### ISSUE THREAD

**Issue by nickkname99** [bluzone/consumer-service#4]
Hi, 

I have the BluFi and Beacons all linked up and provisioned to the cloud, but it will only allow me to create Presence policies. What do I have to do to be allowed to create the other policies (temperature, motion, etc.)

Thanks

**Comment by robert-dare** [comment]
Hi.

Please send me your projectId or your username and I will enable for you.

Regards,

Robert

**Comment by nickkname99** [comment]
Thank you so much!

Username is NThompson@west.com
Project ID is 2281

I really appreciate this.

Thank you very much,
Nick Thompson

**Comment by nickkname99** [comment]
I figured it out! Thank you :+1:

**Comment by nickkname99** [comment]
Nevermind. Still doesn't work

**Comment by nickkname99** [comment]
Username: NThompson@west.com
ProjectID: 2281
