### ISSUE TITLE
Webhook to ActiveMQ

### ISSUE THREAD

**Issue by nickkname99** [bluzone/consumer-service#5]
I am currently trying to use the third party integration on the Bluzone cloud to send JSON messages to a queue in ActiveMQ. However, whenever I try to test the url, It is unable to validate the endpoint and returns HTTP 412.

Is this impossible to get past with ActiveMQ? If not, how do you suggest I go about it?

**Comment by robert-dare** [comment]
How are  you trying to receive the Webhooks from Bluzone?  Via websocket or via Kinesis?

**Comment by nickkname99** [comment]
Via websocket

**Comment by robert-dare** [comment]
This should be as straight forward as writing the body of the message received from the websocket to your ActiveMQ broker.  I have not kept up to date with ActiveMQ for several years, so I am not aware of a WebSocket client being built into the ActiveMQ broker.

You may want to look at Camel.  It may have something.

You should be able to use this supplied reference implementation of a Websocket client and write the bodies of the messages (that are currently just dumped to system.out) to your broker.

**Comment by nickkname99** [comment]
Ok I finally got the webhook to validate the ActiveMQ queue. And when I click test webhook it sends the test message to the queue. The webhook claims it is active.

However, whenever I violate a policy, I continue to get the email that it was violated, however, the JSON message does not get sent to the ActiveMQ queue like the test webhook message does. Do you have any idea why this may be?

**Comment by robert-dare** [comment]
Can you send me your projectId please?

**Comment by nickkname99** [comment]
2281

**Comment by nickkname99** [comment]
Did you find anything about this?

**Comment by robert-dare** [comment]
This is not the proper forum for your issues.

This is a github repository for a reference implementation of a websocket
consumer for Bluzone.  This has nothing to do with ActiveMQ or Webhooks.

Please direct your issues to:  https://developer.bluvision.com/developer/

and more specifically:
https://bluvision.atlassian.net/servicedesk/customer/portal/2
